# dirname to find data
train_name: "whisper"
train_id: "1"
train_name: "music"
model_name: "base"
corpus_name: "jsut_ver1.1"

path:
  download: "./downloads/jsut_ver1.1"
  raw: "data/1117"
  preprocessed: "data/processed_1117/"
  log: "./log"
  checkpoint: "./checkpoint"  # dir to save model

data:
  audio_sampling_rate: 16000 #好像没用
  audio_max_length: 480000
  lang: zh
  frontend: None  #(raw text), pyopenjtalk_kana (kana)
  text_max_length: 120
  train_ratio: 0.9
  val_ratio: 0.1
  timestamps: False
  task: "lyric"

train:
  batch_size: 8
  seed: 3407
  learning_rate: 0.0005
  weight_decay: 0.01
  adam_epsilon: 0.00000001
  warmup_steps: 2
  num_worker: 2
  num_train_epochs: 10 #loss=0.467, v_num=1, train/loss=0.623, val/loss_step=4.64
  gradient_accumulation_steps: 1

inference:
  epoch_index: 2
  temperature: 1.
  top_p: 0.95
  task: translate

  


